---
title: "test_em_est"
output: pdf_document
---

# rtskewt
```{r}
s1 <- matrix(rnorm(4), nrow = 2); s2 <- matrix(rnorm(9), nrow = 3); s3 <- matrix(rnorm(16), nrow = 4)
s1 <- crossprod(s1, s1); s2 <- crossprod(s2, s2); s3 <- crossprod(s3, s3)
rand_mu <- array(rnorm(24, mean = 10), dim = c(2, 3, 4))
rand_skew <- array(rnorm(24), dim = c(2, 3, 4))
nu <- 20
rtskewt_draws <- rtskewt(n = 1e3, mu = rand_mu,
                         sigmas = list(s1, s2, s3),
                         skew = rand_skew, nu = nu)
exp_mu <- rand_mu + (nu/(nu-2)) * rand_skew

#36 seconds to run
(res <- em_est_skewt(rtskewt_draws, quiet = FALSE))

```

Test correctness
```{r}
tensormodels:::frob_norm_diff(s1/(sum(diag(s1))) * 2, res$sigmas[[1]])
tensormodels:::frob_norm_diff(s2/(sum(diag(s2))) * 3, res$sigmas[[2]])
tensormodels:::frob_norm_diff(s3/(sum(diag(s2))) * 4, res$sigmas[[3]])
tensormodels:::frob_norm_diff(exp_mu, res$mu)
tensormodels:::frob_norm_diff(rand_skew, res$skew)
tensormodels:::frob_norm_diff(nu, res$nu)
```

Compare simulated to original
```{r}
library(tidyverse)

sim_rtskewt_draws <- rtskewt(n = 1e3, mu = res$mu, skew = res$skew, 
                             sigmas = res$sigmas, nu = res$nu)

tibble("orig" = rtskewt_draws |> c(),
       "sim" = sim_rtskewt_draws |> c()) |>
  pivot_longer(cols = everything()) |>
  ggplot() +
  geom_histogram(aes(x = value), color = "black", fill = "pink", bins = 40) +
  facet_wrap(~name) +
  theme_minimal()
```


Test across a range of values
```{r, eval = FALSE}
param_grid <- expand_grid(
  mu_scale   = c(0, 1, 2),      # center magnitude
  skew_scale = c(0, 1, 5, 10),  # skew magnitude
  nu         = c(5, 10, 20, 50), # df-like parameter
  n = c(1e3, 1e4)
)

safe_em <- safely(function(mu_scale, skew_scale, nu, n) {
  dims <- c(2, 3, 4)
  mu   <- array(mu_scale, dim = dims)
  skew <- array(skew_scale, dim = dims)

  sigmas <- list(diag(2), diag(3), diag(4))

  draws <- rtskewt(mu = mu, skew = skew, sigmas = sigmas, nu = nu, n = n)

  em_est(draws, model = "skewt")
})

all_res <- pmap(param_grid, safe_em)

saveRDS(all_res, "rtskewt_sim.RDS")
```


Check simulated results
```{r}
readRDS("rtskewt_sim.RDS")

nu_est <- rep(0,  96)

for(i in 1:96) {
  if(!is.null(all_res[[i]]$result)) nu_est[i] <- all_res[[i]]$result$nu
}

rtskewt_sim[[3]]$result$mu

```


# rtvargamma

```{r}
s1 <- matrix(rnorm(4), nrow = 2); s2 <- matrix(rnorm(9), nrow = 3); s3 <- matrix(rnorm(16), nrow = 4)
s1 <- crossprod(s1, s1); s2 <- crossprod(s2, s2); s3 <- crossprod(s3, s3)
rand_mu <- array(rnorm(24, mean = 10), dim = c(2, 3, 4))
rand_skew <- array(rnorm(24), dim = c(2, 3, 4))
scale <- 6
rtvargamma_draws <- rtvargamma(n = 1e3, mu = rand_mu,
                         sigmas = list(s1, s2, s3),
                         skew = rand_skew, scale = scale)
#exp_mu <- rand_mu + (nu/(nu-2)) * rand_skew
(res_vargamma <- em_est(rtvargamma_draws, quiet = FALSE, model = "vargamma"))
```


Test correctness
```{r}
tensormodels:::frob_norm_diff(s1/(sum(diag(s1))) * 2, res_vargamma$sigmas[[1]])
tensormodels:::frob_norm_diff(s2/(sum(diag(s2))) * 3, res_vargamma$sigmas[[2]])
tensormodels:::frob_norm_diff(s3/(sum(diag(s2))) * 4, res_vargamma$sigmas[[3]])
tensormodels:::frob_norm_diff(exp_mu, res_vargamma$mu)
tensormodels:::frob_norm_diff(rand_skew, res_vargamma$skew)
tensormodels:::frob_norm_diff(scale, res_vargamma$gamma)
```


Compare simulated to original
```{r}
sim_rtvargamma_draws <- with(res_vargamma, 
                             rtvargamma(n = 1e3, mu = mu, skew = skew, 
                                        sigmas = sigmas, scale = gamma))

tibble("orig" = rtvargamma_draws |> c(),
       "sim" = sim_rtvargamma_draws |> c()) |>
pivot_longer(cols = everything()) |>
ggplot() +
  geom_histogram(aes(x = value), color = "black", fill = "pink", bins = 40) +
  facet_wrap(~name) +
  theme_minimal()
```
