---
title: 'test_rtnorm'
output: pdf_document
---

Test with sigma 1 being diagonal
```{r}
s1 <- diag(2); s2 <- matrix(rnorm(9), nrow = 3); s3 <- matrix(rnorm(16), nrow = 4)
s1 <- 4 * s1
s2 <- crossprod(s2, s2); s3 <- crossprod(s3, s3)
list_sigmas <- list(s1, s2, s3)
rand_mu <- array(rnorm(24, mean = 10), dim = c(2, 3, 4))
rtnorm_draws <- rtnorm(n = 1e3, mu = rand_mu, sigmas = list(s1, s2, s3))

est_mle <- mle_est(rtnorm_draws)

est_sig <- est_mle$sigmas

num_sigs <- length(dim(est_mle$mu))

p_vals <- rep(0, num_sigs)

for(d in 1:num_sigs) {
  curr_sig <- est_sig[[d]]
  rho <- dim(curr_sig)[[1]]
  f <- 1/2 * (rho - 1) * (rho + 2)
  
  Vn <- det(curr_sig) * (sum(diag(curr_sig))/rho)^(-rho)
  
  test_stat <- -(n - 1) * 2 * log(Vn)

  p_vals[d] <- pchisq(q = test_stat, df = f, lower.tail = FALSE)
}

p_vals
```


Test with sigma 1, 2, 3 being diagonal
```{r}
s1 <- diag(2); s2 <- diag(3); s3 <- diag(4)
s1 <- 4 * s1
s2 <- 2 * s2
s3 <- 8 * s3
rand_mu <- array(rnorm(24, mean = 10), dim = c(2, 3, 4))
rtnorm_draws <- rtnorm(n = 1e3, mu = rand_mu, 
                       sigmas = list(s1, s2, s3))

est_mle <- mle_est(rtnorm_draws)

est_sig <- est_mle$sigmas

num_sigs <- length(dim(est_mle$mu))

p_vals <- rep(0, num_sigs)

for(d in 1:num_sigs) {
  curr_sig <- est_sig[[d]]
  rho <- dim(curr_sig)[[1]]
  f <- 1/2 * (rho - 1) * (rho + 2)
  
  Vn <- det(curr_sig) * (sum(diag(curr_sig))/rho)^(-rho)
  
  test_stat <- -(n - 1) * 2 * log(Vn)

  p_vals[d] <- pchisq(q = test_stat, df = f, lower.tail = FALSE)
}

p_vals
```


Test with sigma 2 being diagonal with some error

```{r}
s1 <- diag(2); s2 <- diag(3); s3 <- diag(4)
s1 <- 4 * s1
s2 <- 2 * s2 + rnorm(9, mean = 0.4, sd = 0.2)
s3 <- 8 * s3
rand_mu <- array(rnorm(24, mean = 10), dim = c(2, 3, 4))
rtnorm_draws <- rtnorm(n = 1e3, mu = rand_mu, 
                       sigmas = list(s1, s2, s3))

est_mle <- mle_est(rtnorm_draws)

est_sig <- est_mle$sigmas

num_sigs <- length(dim(est_mle$mu))

p_vals <- rep(0, num_sigs)

for(d in 1:num_sigs) {
  curr_sig <- est_sig[[d]]
  rho <- dim(curr_sig)[[1]]
  f <- 1/2 * (rho - 1) * (rho + 2)
  
  Vn <- det(curr_sig) * (sum(diag(curr_sig))/rho)^(-rho)
  
  test_stat <- -(n - 1) * 2 * log(Vn)

  p_vals[d] <- pchisq(q = test_stat, df = f, lower.tail = FALSE)
}

p_vals
```


```{r}
sig1_mle <- est_mle$sigmas[[2]]

n <- 1e3

rho <- dim(sig1_mle)[[1]]

f <- 1/2 * (rho - 1) * (rho + 2)

Vn <- det(sig1_mle) * (sum(diag(sig1_mle))/rho)^(-rho)

test_stat <- -(n - 1) * 2 * log(Vn)

pchisq(q = test_stat, df = f, lower.tail = FALSE)

xbar <- apply(rtnorm_draws, 2:4, mean)

d <- 1

tot_sum <- 0

for(i in 1:1e3) {
  centered <- matricization(rtnorm_draws[[i]] - xbar, k = d)
  
  tot_sum <- tot_sum + centered %*% t(centered)
}

tot_sum/(1e3)

tot_sum/sum(diag(tot_sum))
```




```{r}
rand_skew <- array(rnorm(24, mean = 2), dim = c(2, 3, 4))

full_covar <- kronecker(s3, s2) |> kronecker(s1)
inv_covar <- chol2inv(chol(full_covar))

res <- rep(0, 1e3)

for(i in 1:1e3) {
  curr_draw <- rtnorm_draws[i, , ,]
  
  diff <- c(curr_draw - rand_mu)
  
  res[i] <- t(diff) %*% inv_covar %*% diff
}

cutoff <- qchisq(p = 0.95, df = 24)
sum(res > cutoff)

ggplot() +
  geom_histogram(aes(x = res, y = after_stat(density)), 
                 fill = "pink", color = "black") +
  geom_function(fun = dchisq, args = list(df = 24), color = "red") +
  geom_vline(aes(xintercept = cutoff), color = "purple") +
  labs(x = "Vectorized Draws", y = "Density") +
  theme_minimal()
```


```{r}
#rtskewt_draws <- rtskewt(n = 1e3, mu = rand_mu, sigmas = list(s1, s2, s3),
                         #skew = rand_skew, nu = 4)

# full_covar <- kronecker(mle_estimates$sigmas[[3]],
#                         mle_estimates$sigmas[[2]]) |>
#               kronecker(mle_estimates$sigmas[[1]])


# full_covar[1:10]
# full_covar_true[1:10]

#full_covar <- full_covar/sum(diag(full_covar))

# test_norm <- function(draws) {
#   mle_estimates <- mle_est(draws)
#   
#   sample_size <- dim(draws)[1]
#   num_dim <- length(dim(draws)) - 1
#   
#   resids <- rep(0, sample_size)
#   
#   for(i in 1:sample_size) {
#     centered <- draws[i, , ,] - mle_estimates$mu
#     
#       for(d in 1:3) {
#         S_half_inv <- chol2inv(chol(mle_estimates$sigmas[[d]]))
#         centered <- n_prod(centered, S_half_inv, n = d)
#       }
#     resids[i] <- sum(centered^2)
#   }
# }

# 
# for(i in 1:sample_size) {
#   centered <- draws[i, , ,] - mu
# 
#   # Apply whitening: multiply by Sigma_d^{-1/2}
#   for(d in 1:3) {
#     S_half_inv <- chol2inv(chol(sigmas[[d]]))   # Σ_d^{-1/2} Σ_d^{-1/2}ᵀ = Σ_d^{-1}
#     centered <- n_prod(centered, S_half_inv, n = d)
#   }
# 
#   res[i] <- sum(centered^2)   # equivalent to diffᵀ Σ^{-1} diff
# }





res2 <- rep(0, 1e3)

for(i in 1:1e3) {
  curr_draw <- rtnorm_draws[i, , ,]
  
  diff <- c(curr_draw - rand_mu)
  
  res2[i] <- t(diff) %*% inv_covar %*% diff
}

ggplot() +
  geom_histogram(aes(x = res2, y = after_stat(density)), 
                 fill = "pink", color = "black") +
  geom_function(fun = dchisq, args = list(df = 24), color = "red") +
  labs(x = "Vectorized Draws", y = "Density") +
  theme_minimal() 

vec <- c(rtnorm_draws)
```

