---
title: "test_decomps"
output: pdf_document
date: "2026-01-24"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
A <- array(1:24, dim = c(2, 3, 4))

ranks <- c(2, 2, 2)

conflicted::conflict_prefer_all("tensormodels", "rTensor")

dims <- dim(A)
order <- length(dims)

a <- tucker(A, ranks = c(2, 2, 2), max_iter = 1)

tucker_reconstruct(a)

list_mats <- hosvd(A, ranks = ranks)$mats

  for(k in 1:order) {
    dims_multiply <- setdiff(1:order, k)
    
    Y <- n_prod(A, t(list_mats[[dims_multiply[1]]]), dims_multiply[1])
    
    for(k_inner in dims_multiply[2:length(dims_multiply)]) {
      Y <- n_prod(Y, t(list_mats[[k_inner]]), k_inner)
    }
    
    Y_svd <- matricization(Y, k) |> svd(nu = ranks[k])
    
    list_mats[[k]] <- svd(matricization(Y, k), nu = ranks[k])$u
  }
  
  G_core <- n_prod(A, t(list_cores[[1]]), 1)

  for(k_mult in 2:order) {
    G_core <- n_prod(G_core, t(list_cores[[k_mult]]), k_mult)
  }

  list(G = G_core, mats = list_cores)



#A is 2 x 3 x 4

#first mat is 2 x 2
#second mat is 3 x 2
#third mat is 4 x 2



ranks <- c(2, 2, 2)

init <- hosvd(A, ranks)

list_mats <- init$mats
```


```{r}

cp_als <- function(A, R = 2, max_iter = 2000, tol = 1e-3) {
  dims <- dim(A)
  order <- length(dims)
  
  if(any(R > dims)) stop("R must be smaller than all dims")
  
  list_mats <- hosvd(A, ranks = rep(R, order))$mats

  for(i in 1:max_iter) {
    for(k in 1:order) {
      dims_multiply <- setdiff(1:order, k)
      dims_backward <- rev(dims_multiply)
      
      V <- t(list_mats[[dims_multiply[1]]]) %*% list_mats[[dims_multiply[1]]]
      An <- list_mats[[dims_backward[1]]]
      
      for(k_inner in dims_multiply[2:length(dims_multiply)]) {
         V <- V * (t(list_mats[[k_inner]]) %*% list_mats[[k_inner]])
      }
      
      for(curr in dims_backward[-1]) {
        An <- khatri_rao(An, list_mats[[curr]]) 
      }
      
      Xn <- matricization(A, k)
    
      An <- Xn %*% An %*% solve(V)

      lambda <- sqrt(colSums(An^2))
    
      An <- sweep(An, 2, lambda, "/")
      
      list_mats[[k]] <- An
    }
    recon_A <- cp_als_reconstruct(list(lambda = lambda, mats = list_mats))
  
    conv <- frob_norm(A - recon_A) / frob_norm(A)
    
    if(conv < tol) break
  }
  
  if(i == max_iter) message("Reached max iter ", max_iter)
  
  list(lambda = lambda, mats = list_mats)
}

cp_als_reconstruct <- function(cp_als_list) {
  lambda <- cp_als_list$lambda

  mats <- cp_als_list$mats

  dims <- lapply(mats, nrow) |> unlist()
  order <- length(dims)
  
  A_hat <- array(0, dim = dims)
  
  for(r in 1:2) {
    curr <- outer(mats[[1]][, r], mats[[2]][, r])
    
    for(k in 3:order) {
      curr <- outer(curr, mats[[k]][, r])
    }
    
    A_hat <- A_hat + lambda[r] * curr
  }
  A_hat
}

```


```{r}
lambda[r] *
  outer(list_mats[[1]][, r], list_mats[[2]][, r]) |> 
  outer(list_mats[[3]][, r])

n_prod(list_mats[[1]], list_mats[[2]], 2) |> 
  n_prod(list_mats[[3]], 2)

list_mats

lambda

lambda

An
```


```{r}
for(k in 1:order) {
  V <- t(list_mats[[1]]) %*% list_mats[[1]]
  An <- list_mats[[order]]
  
  for(k_inner in setdiff(2:order, k)) {
    V <- V * (t(list_mats[[k_inner]]) %*% list_mats[[k_inner]])
  }
  
  for(curr in setdiff((order-1):1, k)) {
    An <- khatri_rao(An, list_mats[[curr]]) 
  }
  An <- An %*% MASS::ginv(V)  
  Xn <- matricization(A, k)
  
  Mn <- Xn %*% An
}
#2x12

#2x2
#3x2
#4x2

#IJxK

#6x2  4x2
#24x2

hosvd <- function(A, ranks = NULL) {
  dims <- dim(A)
  order <- length(dims)
  
  list_cores <- vector(mode = "list", length = order)
  
  for(k in 1:order) {
    A_mat <- matricization(A, k)
    
    A_mat_svd <- svd(A_mat)
    
    list_cores[[k]] <- A_mat_svd$u[, 1:ranks[k], drop = FALSE]
  }
  
  G_core <- 
    n_prod(A, t(list_cores[[1]]), 1) |>
    n_prod(t(list_cores[[2]]), 2) |> 
    n_prod(t(list_cores[[3]]), 3)

  list(G = G_core, mats = list_cores)
}

my_hosvd <- hosvd(A, ranks = c(2, 2, 2))
rten_hosvd <- rTensor::hosvd(as.tensor(A), ranks = c(2, 2, 2))

rten_hosvd$est

hosvd_reconstruct(my_hosvd)

my_hosvd$G
rten_hosvd$Z

my_hosvd$mats[[3]]
rten_hosvd$U[[3]]

A <- array(1:24, dim = c(2, 3, 4))

res <- hosvd(A, ranks = c(2, 2, 2))

hosvd_reconstruct(res)

n_prod(list_cores[[1]], list_cores[[2]], 1) |> 
  n_prod(list_cores[[1]], list_cores[[2]], 1)

n_prod(G_core, list_cores[[1]], 1) |>
  n_prod(list_cores[[2]], 2) |> 
  n_prod(list_cores[[3]], 3)

TT_SVD_reconstruct <- function(list_cores) {
  dims <- length(list_cores)
  
  reconstruct <- with(list_cores, nm_prod)
  
  reconstruct <- nm_prod(list_cores[[1]], list_cores[[2]], 2, 1)
  
  for(i in 3:dims) {
    reconstruct <- nm_prod(reconstruct, list_cores[[i]], i, 1)
  }
  reconstruct
}

A <- array(1:6000, dim = c(10, 20, 30))

res <- TT_SVD(A, ranks = c(1, 2, 2, 2, 1))

res_acc <- TT_SVD(A, epsilon = 1e-3)

store <- TT_SVD_reconstruct(res_acc)

TTSVD(A_tensor, accuracy = 1e-2) |> TT_SVD_reconstruct()

TT_SVD_reconstruct(TTSVD(A_tensor, accuracy = 1e-1))

nm_prod(res[[1]], res[[2]], 2, 1) |> 
  nm_prod(res[[3]], 3, 1) |> 
  nm_prod(res[[4]], 4, 1)
  
  
nm_prod(res_acc[[1]], res_acc[[2]], 2, 1) |> 
  nm_prod(res_acc[[3]], 3, 1) |> 
  nm_prod(res[[4]], 4, 1)
  

C <- A

r <- c(1, 2, 2, 1)






A_reconstruct <- 
  nm_prod(list_cores[[1]], list_cores[[2]], 2, 1) |> 
  nm_prod(list_cores[[3]], 3, 1)

A_reconstruct

(A - A_reconstruct)
```


```{r}
nm_prod(out.TTSVD$`I-p`, out.TTSVD$`p-J-q`, 2, 1) |> 
  nm_prod(out.TTSVD$`q-K`, 3, 1)
```


```{r}
out.TTSVD$`I-p` 
out.TTSVD$`p-J-q` 
out.TTSVD$`q-K` 
```


```{r}
library("rTensor")
# Tensor data
dimnames(A) <- list(
    I=paste0("i", 1:4),
    J=paste0("j", 1:5),
    K=paste0("k", 1:6))

A_tensor <- as.tensor(A)
# TT-ranks
Ranks <- c(p=2, q=2, r=2)
# TTSVD
out.TTSVD <- TTSVD(A_tensor, Ranks)

out.TTSVD$`I-p` |> dim() #2 x 2
out.TTSVD$`p-J-q` |> dim() #2 x 3 x2
out.TTSVD$`q-K` |> dim() #2 x 4
#row x col




nm_prod(out.TTSVD$`I-p`, out.TTSVD$`p-J-q`, 1, 1) |> 
  nm_prod(out.TTSVD$`q-K`, 1, 1)


ttm(out.TTSVD$`I-p` |> matrix(nrow = 2), out.TTSVD$`p-J-q`, 1)

ttm(as.tensor(out.TTSVD$`p-J-q`), out.TTSVD$`I-p`, m = 1) |> 
  ttm(out.TTSVD$`q-K`, m = 3)

out.TTSVD$`p-J-q`

rTensor::ttm(out.TTSVD$`I-p`, out.TTSVD$`p-J-q`, 1)
```
