// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// mn_mode_prod_cpp
NumericVector mn_mode_prod_cpp(NumericVector A, NumericVector B, int n, int m);
RcppExport SEXP _tensormodels_mn_mode_prod_cpp(SEXP ASEXP, SEXP BSEXP, SEXP nSEXP, SEXP mSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type A(ASEXP);
    Rcpp::traits::input_parameter< NumericVector >::type B(BSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    rcpp_result_gen = Rcpp::wrap(mn_mode_prod_cpp(A, B, n, m));
    return rcpp_result_gen;
END_RCPP
}
// n_mode_prod_cpp
NumericVector n_mode_prod_cpp(NumericVector tensor, NumericMatrix mat, int n);
RcppExport SEXP _tensormodels_n_mode_prod_cpp(SEXP tensorSEXP, SEXP matSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type tensor(tensorSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type mat(matSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(n_mode_prod_cpp(tensor, mat, n));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_tensormodels_mn_mode_prod_cpp", (DL_FUNC) &_tensormodels_mn_mode_prod_cpp, 4},
    {"_tensormodels_n_mode_prod_cpp", (DL_FUNC) &_tensormodels_n_mode_prod_cpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_tensormodels(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
