# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' n-mode product
#'
#' Compute the n-mode product of a tensor with a matrix.
#'
#' @param tensor An array representing the tensor.
#' @param mat A matrix of size \eqn{m \times n} to multiply with.
#' @param n  An integer specifying the mode to multiply across.
#'
#' @return An array: the result of the n-mode product.
#'
#' @examples
#' a <- array(1:3, dim = c(3, 1, 1))
#' x <- matrix(4:9, nrow = 2, ncol = 3)
#' n_prod(a, x, 1)
#'
n_prod <- function(tensor, mat, n) {
    .Call(`_tensormodels_n_prod`, tensor, mat, n)
}

#' nm-mode product
#'
#' Compute the nm-mode product of a tensor with a tensor
#'
#' @param tensor_A An array representing the tensor A.
#' @param tensor_B An array representing tensor B.
#' @param n An integer specifying which mode of tensor A to multiply across.
#' @param m An integer specifying which mode of tensor B to multiply across.
#'
#' @return An array: the result of the nm-mode product between A and B.
#'
#' @examples
#' A <- matrix(c(1, 2, 3, 4), nrow = 2)
#' x <- matrix(c(5, 6), nrow = 2)
#' nm_prod(A, x, 1, 1)
#'
nm_prod <- function(A, B, n, m) {
    .Call(`_tensormodels_nm_prod`, A, B, n, m)
}

#' tensor product
#'
#' Compute the tensor product of a tensor with a tensor
#'
#' @param tensor_A An array representing the tensor A.
#' @param tensor_B An array representing tensor B.
#' @param simplify A bool saying whether to simplify the output. Defaults to TRUE.
#'
#' @return An array: the result of the tensor product between A and B.
#'
#' @examples
#' A <- matrix(c(1, 2, 3, 4), nrow = 2)
#' x <- matrix(c(5, 6), nrow = 2)
#' tensor_prod(A, x)
tensor_prod <- function(A, B, simplify = TRUE) {
    .Call(`_tensormodels_tensor_prod`, A, B, simplify)
}

