# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

mn_mode_prod_cpp <- function(A, B, n, m) {
    .Call(`_tensormodels_mn_mode_prod_cpp`, A, B, n, m)
}

n_mode_prod_cpp <- function(tensor, mat, n) {
    .Call(`_tensormodels_n_mode_prod_cpp`, tensor, mat, n)
}

tensor_prod_cpp <- function(A, B, simplify = TRUE) {
    .Call(`_tensormodels_tensor_prod_cpp`, A, B, simplify)
}

